name: Lint

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: astral-sh/ruff-action@v3
        with:
          src: "."
