name: Lint

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff lint
        run: ruff check . --config ./pyproject.toml
